{{- range $index, $e := until (int $.Values.replicas) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.mode }}-{{ $index }}
  labels:
    app: {{ $.Values.mode }}-{{ $index }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.ports.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ $.Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $.Values.ports.graphql }}
      targetPort: graphql
      protocol: TCP
      name: graphql
    - port: {{ $.Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ $.Values.mode }}-{{ $index }}
  sessionAffinity: ClientIP
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.mode }}
  labels:
    app: {{ $.Values.mode }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.ports.p2p }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ $.Values.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $.Values.ports.graphql }}
      targetPort: graphql
      protocol: TCP
      name: graphql
    - port: {{ $.Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    node: {{ $.Values.mode }}
  sessionAffinity: ClientIP
